FROM maven:3.9.9-eclipse-temurin-17-alpine AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src /app/src
RUN mvn package

FROM openjdk:17-jdk-alpine

EXPOSE 8080

WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]
